baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My Utility Scripts'
theme="tooloo-hugo"

# for search functionality
[outputs]
home = [ "HTML", "JSON" ]

# needed to render the script tag
# that'll load the asciicasts
[markup.goldmark.renderer]
unsafe= true


